version: '3'
services:
  chrome:
    image: selenium/node-chrome:4.0.0
    volumes:
      - /dev/shm:/dev/shm
      - ./download:/home/seluser/Downloads
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4445
      - TZ=Europe/Paris
    shm_size: 512MB
    ports:
      - "6901:5900"
      
  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    # environment:
    #   - SE_OPTS=--log-level FINE
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4445:4444"
    environment:
      - TZ=Europe/Paris